// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Parking.Database;

namespace Parking.DatabaseMigrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parking.Mqtt.Infrastructure.Data.Entities.MqttServerConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CleanSession")
                        .HasColumnType("bit");

                    b.Property<int>("KeepAlive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("TCPServer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseTls")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MqttServerConfigurations");
                });

            modelBuilder.Entity("Parking.Mqtt.Infrastructure.Data.Entities.MqttTopicConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MqttServerConfigurationId")
                        .HasColumnType("int");

                    b.Property<int>("QoS")
                        .HasColumnType("int");

                    b.Property<string>("TopicName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MqttServerConfigurationId");

                    b.ToTable("MqttTopicConfigurations");
                });

            modelBuilder.Entity("Parking.Mqtt.Infrastructure.Data.Entities.MqttTopicConfiguration", b =>
                {
                    b.HasOne("Parking.Mqtt.Infrastructure.Data.Entities.MqttServerConfiguration", null)
                        .WithMany("Topics")
                        .HasForeignKey("MqttServerConfigurationId");
                });
#pragma warning restore 612, 618
        }
    }
}
